theme: "PaperMod"
baseURL: "https://ulambayar0511.github.io/badangel/"
languageCode: 'en-us'
title: "PaperMod"
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true
params:
  env: production 
  title: Blog website
  description: "blog website"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true